docksal/service-cli

- Dockerfile
We are using docksal in combination with the [drupal-composer project](https://github.com/drupal-composer/drupal-project). The Console version in the service cli does not work with that project, see https://github.com/hechoendrupal/drupal-console/issues/3058.
Updating from DrupalConsole beta5 to rc14 solves that problem.
> Updated DrupalConsole 1.0.0-beta5 to drupal-console-launcher 1.0.0-rc14.

- Dockerfile
Adds the bz2 PHP7 extension so the latest version of Acquia BLT installs cleanly.
> Add bz2 as an available PHP7 extension. Required for Acquia BLT.

- Dockerfile
Requested in https://github.com/docksal/service-cli/issues/14
Speeds up installation of composer packages by running requests in parallel see https://github.com/hirak/prestissimo
> Add hirak/prestissimo composer plugin to speed up package installation. Fixes #14

- 5.6/Dockerfile
- 7.0/Dockerfile
- 7.1/Dockerfile
- 7.2/Dockerfile
https://github.com/docksal/docksal/issues/416
The official release sendmail binary is compiled with a version of Go <1.8 which means it doesn't respect the resolvconf option `options ndots:0` when performing DNS lookups.
https://groups.google.com/forum/#!msg/golang-codereviews/aSIWRSuuwDE/hRvAKeoHAwAJ
Here, I've compiled mhsendmail v0.2.0 using golang v1.8.3 and included it in-repo. Dockerfile is modified to copy this binary in rather than curl it from the official release site.
Perhaps a binary shouldn't be in a repo, but preferable to making golang a requirement for building this image?
> Include mhsendmail binary

- 5.6/Dockerfile
- 7.0/Dockerfile
- 7.1/Dockerfile
- 7.2/Dockerfile
`composer` supports using a cache for git repositories since ~1.2, but in order to actually use it, it needs git version `2.3.0-rc0` or newer, because since then it includes the `--dissociate` option. More context on that on the [composer related original PR](https://github.com/composer/composer/pull/5384).
The current cli container is using debian jessie, which has git `2.1.4`.
This change adds jessie backports repository to be able to get a newer one, currently it is `2.11.0`.
> Upgrade Git to get composer git cache

- 5.6/Dockerfile
Installing xdebug without specifiying a version leads to this error:
```
sudo pecl install xdebug
pecl/xdebug requires PHP (version >= 7.0.0), installed version is 5.6.33
```
So i propose to install xdebug-2.5.5 - the last version with php5 support - instead.
I haven't tested if the dockerfile is built correctly, but i asume it does, as the terminal command works in the container.
> Xdebug is missing in docksal/cli:2.0-php5.6

- 5.6/Dockerfile
- 7.2/php-modules.txt
- README.md
- tests/test.bats
- Fixed missing `xdebug` extension for PHP 5.6 (#29)
- Also fixed test checking `xdebug`
- Fixed tests for PHP 7.2
- Added `sodium` to the list of modules for PHP 7.2. It was added upstream.
- Updated README.md (new image tags, misc.)
> Release 2.0.1

- 5.6/Dockerfile
- 5.6/php-modules.txt
- 7.0/Dockerfile
- 7.0/php-modules.txt
- 7.1/Dockerfile
- 7.1/php-modules.txt
- 7.2/Dockerfile
- 7.2/php-modules.txt
- tests/test.bats
- removed archaic/not used extensions
- `mysql` - mysqli or pdo_mysql should be used instead
- `dba`, `shmop`, `sysvmsg`, `sysvsem`, `sysvshm, wddx`
- IMAP support via `imap` extension
- PostgreSQL support via `phsql` and `pdo_pgsql` extensions
- MSSQL support via `sqlsrv` and `pdo_sqlsrv` extensions (PHP 7.0+ only)
> PHP extension updates

- 5.6/Dockerfile
- 5.6/config/php/zz-php.ini
- 5.6/php-modules.txt
- 5.6/startup.sh
- 7.0/Dockerfile
- 7.0/config/php/zz-php.ini
- 7.0/startup.sh
- 7.1/Dockerfile
- 7.1/config/php/zz-php.ini
- 7.1/startup.sh
- 7.2/config/php/zz-php.ini
- 7.2/startup.sh
- README.md
- Silence `terminus auth:login` (otherwise it shows up in `fin run-cli`)
- Fix `id_rsa` key file permissions to avoid ssh warnings (Fixes #44)
- Added a timestamp in `echo-debug` in `startup.sh` (helps better understand container startup times)
- Fixed Blackfire PHP settings (Fixes docksal/docksal#561)
- These got accidentally dropped during the 2.0 cli image upgrade
- Debian Stretch compatibility fix for 5.6, 7.0 and 7.1
- Upstream `php:x.y-fpm` images switched to Debian Stretch. 7.2 was already on Stretch.
Resulting image size changes (compared to 2.1.0):
- php5.6: 359 MB => 297 MB (-62 MB)
- php7.0: 373 MB => 311 MB (- 62 MB)
- php7.1: 373 MB => 312 MB (- 61 MB)
- php7.2: 312 MB => 313 MB (+ 1MB)
> Release 2.2.0

- 5.6/Dockerfile
- 5.6/startup.sh
- 7.0/Dockerfile
- 7.0/startup.sh
- 7.1/Dockerfile
- 7.1/startup.sh
- 7.2/Dockerfile
- 7.2/startup.sh
- README.md
- tests/test.bats
Added tool for Platform.sh Integration.
Updated Readme.md to include `SECRET_PLATFORMSH_CLI_TOKEN` environment variable that is rewritten with `startup.sh` to just `PLATFORMSH_CLI_TOKEN` which is used to authenticate with Platform.sh.
Following Documentation on Platform.sh CLI tool https://github.com/platformsh/platformsh-cli
Platform is another big hosting company alongside Pantheon and Acquia. This integration could be an additional step to a more universal tool and yet another hosting company we can reach out to.
Other customizations through environment variables are as follows
Other customization is available via environment variables:
* `PLATFORMSH_CLI_DEBUG`: set to 1 to enable cURL debugging. _Warning_: this will print all request information in the terminal, including sensitive …
> Added Platform.sh CLI Tool Integration

- 5.6/Dockerfile
- 7.0/Dockerfile
- 7.1/Dockerfile
- 7.2/Dockerfile
- tests/test.bats
See comments in commits for details.
Side note: I experimented and compared installing all PHP tools with composer (`~/.composer/`) vs phar (`/usr/local/bin`) where possible. phar based installation is simpler and the resulting image size is about 40MB smaller. However, compressed image size is only 4MB smaller.
Not sure which method should be considered the best practice. Staying with the phar approach for now.
> PHP tools installation refactoring

- .travis.yml
- 5.6/Dockerfile
- 5.6/startup.sh
- 7.0/Dockerfile
- 7.0/startup.sh
- 7.1/Dockerfile
- 7.1/startup.sh
- 7.2/Dockerfile
- 7.2/startup.sh
- README.md
- cloud9/Dockerfile
- tests/test.bats
- Added `ping` utility
- Removed the git version override
- Debian Stretch ships with git v2.11.0, so the override introduced in #25 is no longer necessary.
- Switched `mssql` and `git-lfs` repos from `jessie` to `stretch`
- Removed packages installed upstream as persistent
- `ca-certificates`, `curl`
- `g++` - we've been considering this a build dependency only, so it was uninstalled at the end of the build. This closes docksal/docksal#713.
- Removed `zsh` (not used)
- Fixed a typo in `chown` in `startup.sh`
- Added tests for essential binaries
- Updated README.md
> Release 2.4.0

- 5.6/startup.sh
- 7.0/startup.sh
- 7.1/startup.sh
- 7.2/startup.sh
> Fix issue with empty SECRET_SSH_PRIVATE_KEY prevent SSH authentication

- 5.6/Dockerfile
- 7.0/Dockerfile
- 7.1/Dockerfile
- 7.2/Dockerfile
- tests/test.bats
Regular Drush doesn't work 100% with Backdrop therefore requires that drush have custom commands installed so that drush can be used with Backdrop.
https://backdropcms.org/project/drush
> Added BackDrop Command

- 5.6/startup.sh
- 7.0/startup.sh
- 7.1/startup.sh
- 7.2/startup.sh
- tests/.docksal/services/cli/startup.sh
- tests/test.bats
The custom startup script doesn't run a the docker user therefore doesn't have access to any of the variables and doesn't have access to any of the items in `$PATH`.
Suggesting changing to run the script as `docker`.
> Run custom startup.sh script as the docker user

- 5.6/config/php/zz-php.ini
- 7.0/config/php/zz-php.ini
- 7.1/config/php/zz-php.ini
- 7.2/config/php/zz-php.ini
- 7.3/config/php/zz-php.ini
Added `--read-envelope-from` option to the sendmail_path in php.ini to resolve "envelope-from address is missing" errors (see https://github.com/docksal/service-cli/issues/116)
> Added --read-envelope-from option for msmtp

- 5.6/Dockerfile
- 7.0/Dockerfile
- 7.1/Dockerfile
- 7.2/Dockerfile
- 7.3/Dockerfile
The -U flag has been a part of shadow [since 4.1.1](https://github.com/shadow-maint/shadow/commit/93e2f66a60). It tries to create a group with the same name and ID as the user (but will potentially use a higher group ID if the user ID is not available as a group ID).
Since the UID is already specified with the `-u` flag, we do not need to specify `1000` a second time for the group or preface `useradd` with `groupadd`.
> Create docker group as part of `useradd` command

- 7.3/Dockerfile
With this small fix it's possible to use xdebug in PHP 7.3 without crashing your application.
> Use latest stable installation candidate for xdebug in PHP 7.3

- 7.1/Dockerfile
- 7.2/Dockerfile
- 7.3/Dockerfile
- Blackfire v1.27.4
- Platform.sh cli v3.49.1
- Terminus v2.2.0
- nvm v0.35.0 / nodejs v12.13.0 LTS / yarn v1.19.1
- Ruby v2.6.5
- pyenv v1.2.14
> Updated versions for cli tools

- 7.1/config/php/zz-php.ini
- 7.2/config/php/zz-php.ini
- 7.3/config/php/zz-php.ini
- tests/scripts/php-fpm.sh
- tests/test.bats
This fixes "msmtp: cannot use both --from and --read-envelope-from" with Drupal 8.
Fixes #142. Reverts #117
> Removed --read-envelope-from in sendmail_path

- 7.1/Dockerfile
- 7.2/Dockerfile
- 7.3/Dockerfile
When `drupal-check` was added in #139 I forgot to make it executable. This fixes that.
> Make the drupal-check binary executable

- 7.2/Dockerfile
- 7.2/php-modules.txt
- 7.3/Dockerfile
- 7.3/php-modules.txt
- 7.4/Dockerfile
- 7.4/php-modules.txt
closes: https://github.com/docksal/service-cli/issues/171
at the moment, xdebug version 2.9.1 is being installed from pecl. so image rebuild will closes: https://github.com/docksal/service-cli/issues/164
> Add sysvsem extension

- 7.2/Dockerfile
- 7.2/ping-web.sh
- 7.3/Dockerfile
- 7.3/ping-web.sh
- 7.4/Dockerfile
- 7.4/ping-web.sh
- README.md
Workaround for https://github.com/docksal/service-vhost-proxy/issues/43
while fin exec is running, background process periodically ping web container (adds new records to web container logs)
> Notify web container about started fin exec inside cli

- .github/scripts/docker-tags.sh
- .github/workflows/default.yaml
- .travis-legacy.yml
- 7.3/Dockerfile
- 7.3/Makefile
- 7.3/startup.sh
- 7.4/Dockerfile
- 7.4/Makefile
- 7.4/startup.sh
- README.md
- tests/test.bats
- Build and CI overhaul
- Switched to GitHub Actions for CI
- Switched to Docker BuilKit for image builds
- Pushing images to Docker Hub as well as GitHub Container Registry
- Updates to console tools
- Switch to official acquia/cli + automated login
- Switched from typhonius/acquia_cli to the official acquia/cli (`acli` binary)
- Config variables changed to `SECRET_ACQUIA_CLI_KEY` and `SECRET_ACQUIA_CLI_SECRET`
- Added `jq` and `yq`
- Dropped `drupal-check`
- composer 1.10.19 + 2.0.8
- drupal console launcher 1.9.7
- platform.sh cli 3.63.3
- nvm 0.36.0, nodejs 14.15.1
- code-server 3.7.4, gitlens 11.0.6
- Fixed `COMPOSER_DEFAULT_VERSION` example in README
- Fixed issue with `gomplate` printing an empty line in `startup.sh`
> Release 2.13.0

- .github/scripts/docker-tags.sh
- .github/workflows/default.yaml
- 7.3/Makefile
- 7.4/Makefile
- README.md
- code-server/Makefile
- tests/test.bats
All newer Docksal images follow this naming convention for tags:
```
<image-repo>:<software-version>[-<image-stability-tag>][-<flavor>]
```
Older images (including docksal/cli today) used this:
```
<image-repo>:[<image-stability-tag>]-<software-version>
```
> Align image tags with other Docksal images

- 7.3/Dockerfile
- 7.3/config/php/xdebug.ini
- 7.4/Dockerfile
- 7.4/config/php/xdebug.ini
* Reverted xdebug port to use 9000 instead of the new 9003 to not introduce breaking change.
> Revert XDebug Port

- 7.3/Dockerfile
- 7.4/Dockerfile
- 8.0/Dockerfile
Project level vendor/bin (`/var/www/vendor/bin`) takes precedence over the global one (`/home/docker/.composer/vendor/bin`).
Fixes #234
> Project level Composer vendor/bin in PATH

- 8.0/Dockerfile
PECL imagick supports PHP 8 starting with v3.5.0
> Switched back to installing imagick from PECL binaries

- 7.4/Dockerfile
- 8.0/Dockerfile
- 8.1/Dockerfile
Currently, when running PHP commands in the CLI container using the a default image, then the php.ini file is not loaded:
```sh
$ fin exec php --ini
Configuration File (php.ini) Path: /usr/local/etc/php
Loaded Configuration File:         (none)
Scan for additional .ini files in: /usr/local/etc/php/conf.d
...
```
This is due to the fact that `php.ini` has not enough permissions:
```sh
$ fin exec ls -al /usr/local/etc/php
total 236
drwxr-xr-x 1 root root  4096 Jul 26 20:03 .
drwxr-xr-x 1 root root  4096 Jul 22 03:10 ..
drwxr-xr-x 1 root root  4096 Dec  7 08:19 conf.d
-rw------- 1 root root 72553 Jan  1  1970 php.ini
-rw-r--r-- 1 root root 72554 Jul 22 03:10 php.ini-development
-rw-r--r-- 1 root root 72584 Jul 22 03:10 php.ini-production
```
This is due to the fact that the php.ini is …
> Fix 'Configuration file loaded: none' in CLI

- 8.1/Dockerfile
- 8.1/tests/php-modules.sh
- Re-enabled gnuphp for PHP 8.1 
- Pecl `gnupg` added support for PHP 8.1 starting with v1.5.1
- Switched to stable sqlsrv (MSSQL) PHP extension for PHP 8.1 
- Pecl `sqlsrv` fully supports for PHP 8.1 starting with v5.10.0
> PHP 8.1 package updates

- 7.4/Dockerfile
- 7.4/config/php/zz-php.ini
- 8.0/Dockerfile
- 8.0/config/php/zz-php.ini
- 8.1/Dockerfile
- 8.1/config/php/zz-php.ini
- tests/test.bats
- Updated blackfire cli to v2.6.0
- Updated blackfire port settings for v2
- Disabled Monitoring (APM) explicitly as Docksal is a dev platform
- Updated tests
Credit / closes: #250, closes #251.
> Update blackfire cli to v2.6.0

- 7.4/config/php/zz-php.ini
- 8.0/config/php/zz-php.ini
- 8.1/config/php/zz-php.ini
- tests/test.bats
This will make `mail()` work out of the box under every circumstance.
Setting the default `--from` option ensures PHP's built-in `mail()` function can be used without extra arguments (currently, you'd have to either set `-f <email>` or `--read-envelope-from`).
This also does not conflict with Drupal/etc., which may also try to pass `-f/--from` as an option in the 5th argument in `mail()`. See https://github.com/docksal/service-cli/issues/264#issuecomment-1046348914
Resolves: #264
Related to #117, which resulted in #142, which lead to #117 being reverted back in #149.
> Updated sendmail_path in php.ini

- 7.4/Dockerfile
- 7.4/tests/essential-binaries.sh
- 8.0/Dockerfile
- 8.0/tests/essential-binaries.sh
- 8.1/Dockerfile
- 8.1/tests/essential-binaries.sh
- Added `bundler` back 
- `bundler` was unintentionally dropped in v3.0.0 along with `rvm`
- Updated the lists of essential binaries 
- Added: `bundler`, `node`, `nvm`, `php`, `python3`, `ruby`
Fixes #272
> Restore bundler

- 7.4/Dockerfile
- 7.4/tests/essential-binaries.sh
- 8.0/Dockerfile
- 8.0/tests/essential-binaries.sh
- 8.1/Dockerfile
- 8.1/tests/essential-binaries.sh
`pip` was lost unintentionally in the v3.0 release. Added a test to check for the `pip` binary.
Fixes #276
> Added python3-pip

- .github/workflows/default.yaml
- 7.4/Dockerfile
- 7.4/tests/essential-binaries.sh
- 8.0/Dockerfile
- 8.0/tests/essential-binaries.sh
- 8.1/Dockerfile
- 8.1/tests/essential-binaries.sh
- tests/test.bats
- Version bumps
- Composer v2.2.10
- Acquia CLI v1.27.0
- Terminus v3.0.7
- Platform.sh CLI v3.77.0
- yq v4.24.2
- Node.js v16.14.0
- nvm v0.39.1
- yarn v1.22.17
- Restored Python `pip`
- `pip` was unintentionally dropped in the v3.0 release
- Added a test to check for the `pip` binary
- Disabled Terminus/Pantheon tests 
- TODO: Figure out why these tests fail sporadically, then re-enable
> Release 3.2.0

- 7.4/Dockerfile
- 8.0/Dockerfile
- 8.1/Dockerfile
- `dealerdirect/phpcodesniffer-composer-installer` - required by `drupal/coder` => `squizlabs/php_codesniffer`
Fixes https://github.com/docksal/service-cli/issues/280
> Set composer global allow-plugins

- .github/workflows/default.yaml
- 7.4/Dockerfile
- 8.0/Dockerfile
- 8.1/Dockerfile
- tests/test.bats
- Version bumps
- PHP 7.4.33 / PHP 8.0.27 / PHP 8.1.14
- tianon/gosu 1.13
- hairyhenderson/gomplate 3.11.3
- composer/composer 2.5.1
- wp-cli/wp-cli 2.7.1
- platformsh/legacy-cli 4.0.2
- acquia/cli 2.7.0 (1.30.1 for PHP 7.4)
- pantheon-systems/terminus 3.1.2
- mikefarah/yq 4.30.8
- nvm-sh/nvm 0.39.3
- node.js 18.13.0 LTS
- yarnpkg/yarn 1.22.19
- coder/code-server 4.9.1
- gitkraken/vscode-gitlens 13.2.0
- xdebug/vscode-php-debug 1.30.0
- Pinning xdebug at 3.1.6 for PHP 7.4
- Increased the timeout in the cronjob test
- Updated versions of GitHub Actions dependencies
> Release 3.3.0

- 8.1/Dockerfile
- 8.2/Dockerfile
- 8.3/Dockerfile
Fixes https://github.com/docksal/service-cli/issues/317
```
docker@cli:/var/www$ which yarn
/home/docker/.nvm/versions/node/v20.11.0/bin/yarn
docker@cli:/var/www$ yarn -v
1.22.22
docker@cli:/var/www$ yarn init -2
➤ YN0000: · Yarn 4.1.1
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: · Done in 0s 96ms
docker@cli:/var/www$ which yarn
/home/docker/.nvm/versions/node/v20.11.0/bin/yarn
docker@cli:/var/www$ yarn -v
4.1.1
```
> Support for corepack yarn installation

- 8.1/Dockerfile
- 8.2/Dockerfile
- 8.3/Dockerfile
Based on the following issue https://github.com/docksal/docksal/issues/1826
Added Install PHP Extension tool
> Added Install PHP Extension tool

- .github/workflows/default.yaml
- Switch to GitHub runners for arm64 builds
- Disabled intermediate tag cleanup on Docker Hub (does not work reliably)
- Bump `docker/build-push-action@v6`
> Switch to GitHub runners for arm64 builds

- 8.1/Dockerfile
- 8.2/Dockerfile
- 8.3/Dockerfile
- 8.4/Dockerfile
- tests/test.bats
- Install SQLite from Debian Trixie (testing) repo 
- SQLite v3.45+ required for Drupal 11
- Platform.sh CLI v5.0.23 
- Replaced `platformsh/legacy-cli` with `platformsh/cli`
- Locale setup fix
Resolves #326. Closes #327
> SQLite, Platform.sh CLI, misc

- .github/workflows/default.yaml
- Fixed PHP 8.4 image push
- Switched `bats-core/bats-action` to v3.0.1
- Switched GitHub Actions to `ubuntu-24.04` runners
> Release 3.9.1
