docksal/service-cli

.travis.yml
scripts/docker-push.sh

- Moved the push script into a standalone file - scripts/docker-push.sh
- Refactored and optimized the script logic

Make sure the latest release and stable tags match. Closes #56

---

tests/test.bats

Added test to confirm Terminus is working correctly in the container.

Added Terminus test

---

README.md

Improved sentence readability and set links to targets that are better for accessibility.

Updated README readability and link accessibility

---

.travis.yml

Docker push script isn't being ran as travis cannot find the docker-push.sh script

Fixed issue with calling docker-push

---

scripts/docker-push.sh

Checked to confirm that TRAVIS_PULL_REQUEST is not false

Fixed is_pr function

---

5.6/Dockerfile
7.0/Dockerfile
7.1/Dockerfile
7.2/Dockerfile
cloud9/Dockerfile
cloud9/Makefile
cloud9/config/supervisord-cloud9.conf
cloud9/tests/test.bats

Switched back to installing node via nvm and made Cloud9 work with it.

Cloud9 compatibility with nvm

---

5.6/Dockerfile
5.6/php-modules.txt
7.0/Dockerfile
7.0/php-modules.txt
7.1/Dockerfile
7.1/php-modules.txt
7.2/Dockerfile
7.2/php-modules.txt

This is a replacement PR for #79

Add APCu pecl extension. Fixes #75. Closes #79

---

5.6/Dockerfile
7.0/Dockerfile
7.1/Dockerfile
7.2/Dockerfile
tests/test.bats

Fixes #76 
* Added WordPress Coding Standard Library.
* Added tests to make sure PHPCS is loading properly.

WordPress CS Library

---

5.6/Dockerfile
5.6/config/.terminus/config.yml
7.0/Dockerfile
7.0/config/.terminus/config.yml
7.1/Dockerfile
7.1/config/.terminus/config.yml
7.2/Dockerfile
7.2/config/.terminus/config.yml

Added terminus config.yml file to hide messages from Terminus. This can cause issues if trying to script output.

Added config.yml for terminus to hide messages

---

5.6/Dockerfile
7.0/Dockerfile
7.1/Dockerfile
7.2/Dockerfile
README.md
tests/test.bats

Install ruby and python specified versions.
Added tests for ruby and python.
Fix for PHPCS Coding standards check test.

Install ruby and python specified versions, added tests for ruby and python.

---

scripts/docker-push.sh

Tag major image versions in addition to minor versions. Resolves #61

---

5.6/Dockerfile
7.0/Dockerfile
7.1/Dockerfile
7.2/Dockerfile
7.3/Dockerfile

Hello,
This pull request will merge in the updates to the Dockerfile, to allow usage of Terminus 2.0.0.
Let me know if me know if there are any questions or if any revisions are needed.
Thank you,
Will Jackson
---
Closes docksal/docksal#978

Update for Terminus 2.0.0

---

7.1/Dockerfile
7.2/Dockerfile
7.3/Dockerfile

Update versions of tools within the container. Mainly drush, drupal launcher, composer, and platform cli.

Updated versions of dev tools

---

7.1/Dockerfile
7.2/Dockerfile
7.3/Dockerfile

Adds [optimization package](https://packagist.org/packages/zaporylie/composer-drupal-optimizations) as a global composer requirement. This package is recommended as part of large Drupal composer projects and recommended for global install.

adds global composer package for Drupal optimizations

---

7.1/Dockerfile
7.1/startup.sh
7.2/Dockerfile
7.2/startup.sh
7.3/Dockerfile
7.3/startup.sh

- Switch to Debian 10 (Buster) based upstream PHP-FPM images (closes #131)

Release 2.8.0

---

7.1/Dockerfile
7.2/Dockerfile
7.3/Dockerfile

Add the drupal-check phar file to CLI

---

scripts/docker-push.sh

Release 2.10.2

---

7.1/config/php/zz-php.ini
7.2/config/php/zz-php.ini
7.3/config/php/zz-php.ini
tests/test.bats

Removed PHP CLI memory limit

---

7.1/Dockerfile
7.2/Dockerfile
7.3/Dockerfile

Adds SVG support to ImageMagick

---

7.2/Dockerfile
7.3/Dockerfile
7.4/Dockerfile

MR for https://github.com/docksal/service-cli/issues/168

Update Platform.sh CLI version to current latest version

---

7.2/Dockerfile
7.2/config/supervisor/supervisord-code-server.conf.tmpl
7.2/opt/code-server/settings.json
7.3/Dockerfile
7.3/config/supervisor/supervisord-code-server.conf.tmpl
7.3/opt/code-server/settings.json
7.4/Dockerfile
7.4/config/supervisor/supervisord-code-server.conf.tmpl
7.4/opt/code-server/settings.json
tests/test.bats

Fixes: https://github.com/docksal/docksal/issues/1254
Added files associations
Changed settings.json file owner to docker
VS Code upgraded to 3.3.1 version

Fix VS Code settings

---

7.2/Dockerfile
7.3/Dockerfile
7.4/Dockerfile
README.md

Fixes: https://github.com/docksal/docksal/issues/1062

Add acquia cli tool

---

7.4/Dockerfile

Fixes #185 
- https://github.com/docker-library/php/issues/912
- https://github.com/php/php-src/blob/PHP-7.4/UPGRADING#L761-L770

Fix jpeg support in GD with PHP 7.4

---

.github/scripts/docker-tags.sh
.github/workflows/default.yaml
.travis-legacy.yml
7.3/Makefile
7.4/Makefile

- Switched to GitHub Actions for CI
- Switched to Docker BuilKit for image builds
- Pushing images to Docker Hub as well as GitHub Container Registry

Build and CI overhaul

---

7.3/Dockerfile
7.4/Dockerfile

Added in JQ as a tool that can be utilized. Primarily we can use it to better assist in the `fin pull` command additionally parsing any json data.

Added JQ as part of tools

---

7.3/Dockerfile
7.3/startup.sh
7.4/Dockerfile
7.4/startup.sh
README.md
tests/test.bats

Added automated login into Acquia CLI using the same mechanism as Terminus.
Closes #199

Switch to official acquia/cli + automated login

---

7.3/Dockerfile
7.4/Dockerfile

ssh2 PHP library can be install from Pecl as ssh2-beta

Install ssh2 from Pecl

---

7.3/Dockerfile
7.3/config/php/xdebug.ini
7.4/Dockerfile
7.4/config/php/xdebug.ini

* Modified Docker Images to listen on port 9003 the new Xdebug
* Modified xdebug configuration
Closes #201

Xdebug Version 3

---

7.3/Dockerfile
7.4/Dockerfile
8.0/Dockerfile
README.md

updates name and links to documentation for provider tools

---

7.3/Dockerfile
7.3/config/code-server/User/settings.json
7.3/config/code-server/config.yaml.tmpl
7.3/config/supervisor/supervisord-code-server.conf.tmpl
7.3/healthcheck.sh
7.3/opt/code-server/install-vscode-extension
7.3/startup.sh
7.4/Dockerfile
7.4/config/code-server/User/settings.json
7.4/config/code-server/config.yaml.tmpl
7.4/config/supervisor/supervisord-code-server.conf.tmpl
7.4/healthcheck.sh
7.4/opt/code-server/install-vscode-extension
7.4/startup.sh
8.0/Dockerfile
8.0/config/code-server/User/settings.json
8.0/config/code-server/config.yaml.tmpl
8.0/config/supervisor/supervisord-code-server.conf.tmpl
8.0/healthcheck.sh
8.0/opt/code-server/install-vscode-extension
8.0/startup.sh

- Replaced manual extension installation script with "code-server --install-extension"
- Switched from command line configuration to config.yaml template
- Set "Default Dark+" theme in user config
Related: https://github.com/docksal/docksal/pull/1534

VS Code Server setup overhaul

---

7.4/Dockerfile
8.0/Dockerfile
8.1/Dockerfile
LICENSE
README.md
tests/test.bats

- Switched to Debian 11 (bullseye) PHP FPM base image
- Updated tests
- Updated docs
Resolves #265, resolves docksal/docksal#1616

Debian 11 (bullseye)

---

.github/workflows/default.yaml

- Updated ARM64 host user (build-agent) for test job

Release 3.2.1

---

7.4/Dockerfile
8.0/Dockerfile
8.1/Dockerfile

- Code Server v4.2.0
- Gitlens v12.0.5
- Xdebug v1.25.0

VS Code Server version bumps

---

.github/workflows/default.yaml
8.1/Dockerfile
8.2/Dockerfile
8.3/Dockerfile

composer 2.7.0 => 2.7.1
wpcli 2.9.0 => 2.10.0
acquia cli 2.22.1 => 2.22.2
yq 4.40.5 => 4.40.7

updates tools

---

.github/workflows/default.yaml
8.4/.dockerignore
8.4/Dockerfile
8.4/Makefile
8.4/config/.ssh/config
8.4/config/.ssh/id_rsa.tmpl
8.4/config/.terminus/config.yml
8.4/config/code-server/User/settings.json
8.4/config/code-server/config.yaml.tmpl
8.4/config/php/opcache.ini
8.4/config/php/xdebug.ini
8.4/config/php/xhprof.ini
8.4/config/php/zz-php-fpm.conf
8.4/config/php/zz-php.ini
8.4/config/supervisor/supervisord-code-server.conf.tmpl
8.4/config/supervisor/supervisord-crond.conf
8.4/config/supervisor/supervisord-php-fpm.conf
8.4/config/supervisor/supervisord-sshd.conf
8.4/config/supervisor/supervisord.conf
8.4/healthcheck.sh
8.4/ping-web.sh
8.4/startup.sh
8.4/tests/essential-binaries.sh
8.4/tests/php-modules.sh

Added PHP 8.4 image
